name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: PHPUnit and Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install Node dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Jest
        run: npm test

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: PHPUnit
        run: vendor/bin/phpunit
